/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four 
million, find the sum of the even-valued terms.
*/

function fib(index){
    if(index == 0)
	return 0;
    if(index == 1)
	return 1;
    else
	return fib(index-2) + fib(index-1)
}
var sum = 0;
var seq = '';
for(i=0;i<34;i++){
    var num = fib(i);
    if(num%2==0){
	sum += num;
	seq += fib(i) + ', ';
    }
}
seq = seq.slice(0,seq.length-2);
console.log(seq);
console.log(sum);
